package com.sparrowwallet.drongo.protocol;

import com.sparrowwallet.drongo.Utils;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * The BLAKE2b header format, checked against two independent oracles.
 *
 * <p>Knots' published vectors prove the port faithful to the C++. The live
 * testnet4 headers prove the reading of the format correct, which the vectors
 * cannot: they are generated by the same code this mirrors, while a live block
 * hash is what the network agreed on.
 */
public class BlockHeaderV2Test {
    @Test
    public void matchesPublishedVectors() throws IOException {
        String json = readResource("/block_header_v2.json");
        List<String[]> vectors = extractVectors(json);
        assertEquals(5, vectors.size(), "expected 5 published vectors");

        for(String[] v : vectors) {
            String name = v[0], serialized = v[1], expectedHash = v[2];
            byte[] raw = Utils.hexToBytes(serialized);
            assertEquals(BlockHeaderV2.HEADER_V2_LENGTH, raw.length, name + ": wire size");
            assertTrue(BlockHeaderV2.isV2(raw, 0), name + ": should be flagged v2");

            BlockHeader header = new BlockHeader(raw);
            assertTrue(header.isV2(), name + ": parsed as v2");
            assertEquals(expectedHash, header.getHash().toString(), name + ": block hash");
            assertArrayEquals(raw, header.bitcoinSerialize(), name + ": roundtrip");
        }
    }

    /**
     * Headers taken off the live BLAKE2b testnet4, frozen in as constants.
     *
     * <p>149537 is the activation block, 149538 chains onto it, so a wrong hash
     * cannot also satisfy the next header's prevBlockHash.
     */
    @Test
    public void matchesLiveTestnet4Headers() {
        String[][] live = {
            {"149537", "000000000068f60429c933dc0c8befbcc7edadb1cf8f8d0d7804c608fd736d82",
             "000000a05119dc259b59eaefbccf48ecc15bfd50c499d9d65b500b361b1b60000000000063be46460c5e75edfe6e1fba731e3fc096396af99c299e70625484ffc6f9184101fb896affff001d986cd88b510d792301fb896a00000000b14cf00d0100000000000000000000000f00000000000000000000000000000000000000214802000000000000000000000000000000000000000000000000000000000000000000"},
            {"149538", "000000000008b8d8f1ce043359100c971e3e0db6bb8ae8ac8618f554564d9177",
             "000000a0826d73fd08c604780d8d8fcfb1adedc7bcef8b0cdc33c92904f6680000000000a56c8509d818afaadcea27a066a820f5c8ac610bb0f8bc297528a52e8bf6c2d202fb896affff001dbe7b778a800e881f02fb896a00000000b10cf00d0100000000000000000000000100000000000000000000000000000000000000224802000000000000000000000000000000000000000000000000000000000000000000"},
        };

        BlockHeader previous = null;
        for(String[] entry : live) {
            byte[] raw = Utils.hexToBytes(entry[2]);
            BlockHeader header = new BlockHeader(raw);
            assertTrue(header.isV2(), entry[0] + ": should be v2");
            assertEquals(entry[1], header.getHash().toString(), entry[0] + ": block hash");
            //The committed height is a second, independent check on the field offsets.
            assertEquals(Long.parseLong(entry[0]), header.getV2().getHeight(), entry[0] + ": committed height");
            assertArrayEquals(raw, header.bitcoinSerialize(), entry[0] + ": roundtrip");
            if(previous != null) {
                assertEquals(previous.getHash(), header.getPrevBlockHash(),
                        entry[0] + " must chain onto the previous header");
            }
            previous = header;
        }
    }

    /** A v1 header must be untouched: same length, same SHA256d hash, no v2 state. */
    @Test
    public void leavesV1HeadersAlone() {
        //Bitcoin mainnet genesis.
        byte[] raw = Utils.hexToBytes("0100000000000000000000000000000000000000000000000000000000000000000000003b"
                + "a3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4a29ab5f49ffff001d1dac2b7c");
        assertEquals(80, raw.length);
        BlockHeader header = new BlockHeader(raw);
        assertFalse(header.isV2());
        assertNull(header.getV2());
        assertEquals("000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f", header.getHash().toString());
        assertArrayEquals(raw, header.bitcoinSerialize());
    }

    /** The length is readable from the version field alone, which is what lets a mixed run be walked. */
    @Test
    public void lengthComesFromTheVersionField() {
        byte[] v2 = Utils.hexToBytes("000000a0" + "00".repeat(160));
        assertEquals(BlockHeaderV2.HEADER_V2_LENGTH, BlockHeaderV2.headerLength(v2, 0));
        byte[] v1 = Utils.hexToBytes("00000020" + "00".repeat(76));
        assertEquals(BlockHeaderV2.HEADER_V1_LENGTH, BlockHeaderV2.headerLength(v1, 0));
    }

    private static String readResource(String path) throws IOException {
        try(InputStream is = BlockHeaderV2Test.class.getResourceAsStream(path)) {
            assertNotNull(is, "missing test resource " + path);
            return new String(is.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    /** Minimal extraction of (name, serialized, block_hash) so the test needs no JSON library. */
    private static List<String[]> extractVectors(String json) {
        List<String[]> out = new ArrayList<>();
        int i = 0;
        while((i = json.indexOf("\"name\"", i)) >= 0) {
            String name = valueAfter(json, i);
            int ser = json.indexOf("\"serialized\"", i);
            int hash = json.indexOf("\"block_hash\"", i);
            if(ser < 0 || hash < 0) {
                break;
            }
            out.add(new String[]{name, valueAfter(json, ser), valueAfter(json, hash)});
            i = Math.max(ser, hash) + 1;
        }
        return out;
    }

    private static String valueAfter(String json, int keyIndex) {
        int colon = json.indexOf(':', keyIndex);
        int open = json.indexOf('"', colon);
        int close = json.indexOf('"', open + 1);
        return json.substring(open + 1, close);
    }
}
